### PR TITLE
Merges cad-staging to main for LumenPnP v3.1.0 release

### LINKED ISSUE #627: Add clearance for access to bolt heads on Y gantries
This is more of an improvement than an issue, but it'd be nice to be able to access these screw heads on the Y gantries, should be a pretty simple cad change.

PXL_20221107_1911525262

### LINKED ISSUE #629: Chamfer m3 nut holes to fix elephant's foot
PXL_20221107_220029310_2

The elephant's foot on the first layer is preventing the m3 nuts from being inserted easily. I used a knife to trim off the elephant's foot which worked, but it'd be great if the first layer or two were chamfered so printers that aren't 100% fine tuned can still make working parts off the print bed with no post processing.

### LINKED ISSUE #656: V3.02 Camera focus
I had great difficulty getting the cameras to focus.  I did print the suggested 3d tool which was some help on the top camera.
However the access to the bottom camera is so tight that the tool did not provide much benefit.
I wound up disassembling the bottom camera and found that the focus lock screw had been over torqued causing the threads
to be munged.  A careful thread repair with an exacto blade and some very small amount of lubricant completely solved the focusing difficulty.   

Please inform the assembly house to not over tighten the camera focus lock screw.

### LINKED ISSUE #659: Need strain relief on Z-gantry...
The connecting wires between the Z-gantry and the head itself are under a fair deal of stress:
In particular, if the connection breaks (yellow wire in my case) the tool head itself gets very hot and deforms the z-gantry.

### LINKED ISSUE #667: Toolhead idler pulley rubs against screw and 3D printed part
# Version Number
3.0.5

# Bugfix or Enhancement
Issue

# Description
The toolhead GT2 idler pulley may rub against screw and x-gantry-front.  Depending on the exact model of the pulley, the bearing surface rubs against the screw, and also with the 3D printed part, causing friction. I can confirm this is an issue with my build. My 3D printer is correctly calibrated and the screw is the same one as the one stated in the BOM. 

image

# Suggested Solution
Make 3D printed contact surface a tiny bit smaller in diameter at the tip, and add an optional washer (it may be 3D printable) to the side of the screw head. The washer has to be small enough to not cause the same problem it's trying to fix.

### LINKED ISSUE #676: Linear Rail Bolts Marginally Interfere with X Gantry Back
# Version Number
V3.1.0

# Bugfix or Enhancement
Bug

# Description
The linear rail mounting bolts intersect x-gantry-back by 0.15mm 
Screenshot 2023-08-30 at 4 15 46 PM

# Suggested Solution
Lower the affected face on x-gantry-back by 2mm

### PR DESCRIPTION
**Pull request by lucy-chapar**
## Adds linear rails to LumenPnP x-gantry and y-gantries ##
Merges @theacodes's[ linear rail mod](https://github.com/theacodes/3d-prints/tree/e6e8d3fad902d00bb780c3391630ff6f85cc4b5d/lumen/linear%20rail%20mod%20(v3)) with the following improvements: 
 - Consolidates toolhead 3D prints by merging the `x-gantry-block` design into `x-gantry-back` 
        - `x-gantry-front` now attaches directly to `x-gantry-back` with 4x `M5x40mm-socket-head` bolts to greatly improve rigidity
 -  Adds insertion clearance for installing `m5-hex-nut` into `y-gantry`
 
toolhead-exploaded-view

## Extends height of machine by 50mm ##
This change was made to improve tape clearance when exiting auto feeders. Affects the following parts
 - `aux-staging-plate-foot`
 -  `static camera foot`
 -  `front-leg-extension` (_new_)
 -  `back-leg-extension` (_new_)
 -  `front-left-leg` / `front-right-leg`
 -  `back-leg`

v3-1-0-render

## Improves machine toolhead ##
 -  Rotates toolhead motors 90º to improve cable routing
 - Adds zip-tie channel in `z-gantry` for toolhead cable strain-relief
 -  Updates pneumatic coupler to `rotary-pneumatic-adapter` to support continuous toolhead rotation
 
toolhead-cable-color-request

## Improves top-camera assembly ##
 - Adds a tunnel around the `focus-adjustment-screw` for ease of use
 - Adds air flow vents to `top-camera-mount` to improve cooling
 - Adds `top-camera-cover` to better protect `top-camera`
 - Adds new region to `top-light-cover` to cover `top-ring-light` THT pins

Screenshot 2023-09-01 at 12 09 18 PM

## Additional changes ##
 - Updates `nozzle-rack` to support tool-free removal from `staging-plate` with use of 2x `m3-wing-nut`
 - Adds mid-air hole print optimizations wherever needed
 - Adjusted various component tolerances for ease of assembly
 - Smoothed out many parts in this assembly where possible to better unify design language

### CODE REVIEW

**Comment by stuartpittaway** [comment]
This looks great @lucian151.  Feel like the comments in ```DESIGN_DECISIONS.md``` need to be updated at the same time as this release - there are lots of points about not using linear rails - but now we are!

**Comment by theacodes** [comment]
Looks good to me, agreed with @stuartpittaway that we should also update `DESIGN_DECISIONS.md`. I'll add a commit here for that.

**Review by theacodes — APPROVED** [review]

**Comment by lucian151** [comment]
Thanks for the changes to the design decision doc @theacodes! We still need to tweak the language of the "Why not CoreXY?" section as it still relates back to v-wheel. Maybe @sphawes would be best to author those changes.

Before this is all released, we need to revert the FTP strip feeder design back to the fileset used in v3.0.5. The strip-feeder refactor won't be ready in time for launch.

**Comment by sphawes** [comment]
Just updated the CoreXY section to remove the mention of rollers!

**Comment by lucian151** [comment]
Alright, thanks y'all! Your feedback has been addressed. Time to merge! 🦾

**Pull request merged**
