### PR TITLE
Merges cad-staging into main for v3.2.1 release prep

### PR DESCRIPTION
**Pull request by lucy-chapar**

### CODE REVIEW

**Comment by lucian151** [comment]
@sphawes please let me know if @G-Pereira's changes are safe to merge!

**Comment by G-Pereira** [comment]
I've triggered a GitHub Actions workflow so we are sure. It has been a while since I've worked on this.

**Comment by lucian151** [comment]
The image of `x-gantry-back` did not appear in the rendered BOM correctly. I'm rerunning the GitHub action with debugging enabled now to see what's up. Results will be here: https://github.com/opulo-inc/lumenpnp/actions/runs/8239352059

**Comment by lucian151** [comment]
OK it worked this time after changing nothing...

**Comment by lucian151** [comment]
can we delete this old branch https://github.com/opulo-inc/lumenpnp/tree/fix-stl-zip-on-zip ?

**Pull request merged**
